-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 11:18:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen2` DEFAULT CHARACTER SET utf8 ;
USE `Examen2` ;

-- -----------------------------------------------------
-- Table `Examen2`.`table1`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `Examen2`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2`.`Produto` (
  `CodigoProducto` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL NULL,
  `Existencias` INT NULL,
  PRIMARY KEY (`CodigoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2`.`Pedido` (
  `CodigoPedido` INT NOT NULL,
  `CodigoProducto` INT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  `Precio` DECIMAL NULL,
  `Total` DECIMAL NULL,
  PRIMARY KEY (`CodigoPedido`),
  INDEX `FK_Pedido_Producto_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `FK_Pedido_Producto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `Examen2`.`Produto` (`CodigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2`.`Usuario` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Clave` VARCHAR(20) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
